# Autogenerated wrapper script for embree_jll for x86_64-unknown-freebsd
export libembree3

using oneTBB_jll
using GLFW_jll
using JpegTurbo_jll
using libpng_jll
JLLWrappers.@generate_wrapper_header("embree")
JLLWrappers.@declare_library_product(libembree3, "libembree3.so.3")
function __init__()
    JLLWrappers.@generate_init_header(oneTBB_jll, GLFW_jll, JpegTurbo_jll, libpng_jll)
    JLLWrappers.@init_library_product(
        libembree3,
        "lib/libembree3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
